import xlsxwriter
import os
import glob
import shutil
import subprocess
   
# Convert Oracle SQL to Postgres SQL
# Workarea SQL
p_sql_work_area = "C:/DB_Scripts/xml_sql_processing/scripts/ora2pg_work_area/oracle_sql_file.sql"
p_pg_output_file = 'xml_sql.sql'
p_ora2pg_output_folder = "C:/DB_Scripts/ora2pg_output/"
p_ora2pg_comments = """-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.0.1.102;SERVICE_NAME=PRISM;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

"""


def ora2pg_output_sql(p_oracle_sql):

    # Write Oracle SQL to Work Area File
    f = open(p_sql_work_area, "w")
    f.write(p_oracle_sql)
    f.close()

    # Convert Oracle SQL to PG SQL
    # ora2pg -p -t QUERY -i C:\DB_Scripts\xml_sql_processing\scripts\ora2pg_work_area\oracle_sql_file.sql -o xml_sql.sql

    l_work = ['ora2pg', '-p', '-t', 'QUERY', '-i' ,p_sql_work_area, '-o', p_pg_output_file]
    subprocess.call(l_work, shell=True)

    # Read Coverted PG sql to variable
    try:
        with open(p_ora2pg_output_folder+p_pg_output_file) as f:
            lines = f.readlines()
            # print("file content")
            # print(lines[-2].strip())
            lines = ''.join(lines).strip()
            lines = lines.replace(p_ora2pg_comments,"")
            return [0,lines]
    except:
        return [1,p_oracle_sql]


def tracker_builder(p_folder_file, p_header, p_data):

    l_row_num = 0
    
    workbook = xlsxwriter.Workbook(p_folder_file)
    worksheet = workbook.add_worksheet("TRACKER")

    header_format = workbook.add_format({'bold': True,
                                         'bottom': 1,
                                         'top': 1,
                                         'left': 1,
                                         'right': 1,
                                         'bg_color': '#F9DA04'})

    for col_num, data in enumerate(p_header):
        worksheet.write(l_row_num, col_num, data, header_format)

    l_row_num += 1
    for l_row in p_data:
        for col_num, data in enumerate(l_row):
            worksheet.write(l_row_num, col_num, data)
        l_row_num += 1

    workbook.close()


l_file_name = 'C:/DB_Scripts/xml_sql_processing/xml_tracker.xlsx'
l_header = ['FILE_NAME','NAVISITE_SQL_ID','DEVELOPER','STATUS','NOTES','ORA_SQL','PG_SQL']
l_data = [['FILE_NAME1','NAVISITE_SQL_ID1','DEVELOPER','STATUS','NOTES','ORA_SQL','PG_SQL']
         ,['FILE_NAME2','NAVISITE_SQL_ID2','DEVELOPER','STATUS','NOTES','ORA_SQL','PG_SQL']
         ,['FILE_NAME3','NAVISITE_SQL_ID3','DEVELOPER','STATUS','NOTES','ORA_SQL','PG_SQL']]

tracker_builder(p_folder_file=l_file_name, p_header=l_header, p_data=l_data)
